name: GitHub Actions Demo

on: 
  push:
    branches:
      - 'main'
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: environment
        required: true
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - run: echo ${{github.event_name}}
      - run: echo ${{github.ref}}
      
      - uses: actions/checkout@main
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  Test:
    name: Test
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Test

    steps:
      - run: echo "Testing..."

  Load-Test: 
    name: Load Test
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test 

    steps:
      - run: echo "Testing..."
      - run: sleep 15

  Production:
    name: Production
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'

    steps:
      - run: |
          echo "Step 1 deploying..."      
          sleep 10 
      - run: |
          echo "Step 2 deploying..."      
          sleep 10
      - run: |
          echo "Step 3 deploying..."      
          sleep 10
      - run: |
          echo "Step 4 deploying..."      
          sleep 10
      - run: |
          echo "Step 5 deploying..."      
          sleep 10
